-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.answer_entity
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    question_id bigint,
    response_id bigint,
    CONSTRAINT answer_entity_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.check_box_answer
(
    id bigint NOT NULL,
    CONSTRAINT check_box_answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.check_box_answer_answer
(
    check_box_answer_id bigint NOT NULL,
    answer character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.date_answer
(
    answer date,
    id bigint NOT NULL,
    CONSTRAINT date_answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.number_answer
(
    answer double precision NOT NULL,
    id bigint NOT NULL,
    CONSTRAINT number_answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.question_entity
(
    "position" integer NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    questionnaire_id bigint,
    answer_configuration text COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    rule_configuration text COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT question_entity_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.questionnaire_entity
(
    published boolean NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    valid_from timestamp(6) without time zone,
    valid_to timestamp(6) without time zone,
    description character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT questionnaire_entity_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.questionnaire_tags
(
    questionnaire_id bigint NOT NULL,
    tags character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.radio_button_answer
(
    id bigint NOT NULL,
    answer character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT radio_button_answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.response_entity
(
    completion_time timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    questionnaire_id bigint,
    user_id bigint,
    CONSTRAINT response_entity_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.slider_answer
(
    answer integer NOT NULL,
    id bigint NOT NULL,
    CONSTRAINT slider_answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.text_answer
(
    id bigint NOT NULL,
    answer character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT text_answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.time_answer
(
    answer time(6) without time zone,
    id bigint NOT NULL,
    CONSTRAINT time_answer_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.answer_entity
    ADD CONSTRAINT fkl61nfbgcn8xrd64yl9dmt5iu0 FOREIGN KEY (response_id)
    REFERENCES public.response_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.check_box_answer
    ADD CONSTRAINT fkfqjbq2yc3iv9vys5odab5327x FOREIGN KEY (id)
    REFERENCES public.answer_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS check_box_answer_pkey
    ON public.check_box_answer(id);


ALTER TABLE IF EXISTS public.check_box_answer_answer
    ADD CONSTRAINT fkslimmji6xpupslcsbiycww0dr FOREIGN KEY (check_box_answer_id)
    REFERENCES public.check_box_answer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.date_answer
    ADD CONSTRAINT fkj30o252gxt0am0ga50aejiukb FOREIGN KEY (id)
    REFERENCES public.answer_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS date_answer_pkey
    ON public.date_answer(id);


ALTER TABLE IF EXISTS public.number_answer
    ADD CONSTRAINT fkc8kt42rf48s2w8u65w84plhvx FOREIGN KEY (id)
    REFERENCES public.answer_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS number_answer_pkey
    ON public.number_answer(id);


ALTER TABLE IF EXISTS public.question_entity
    ADD CONSTRAINT fk_questionnaire_id FOREIGN KEY (questionnaire_id)
    REFERENCES public.questionnaire_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.questionnaire_tags
    ADD CONSTRAINT fkgha6p8i0fw9g8guvfxblh5xju FOREIGN KEY (questionnaire_id)
    REFERENCES public.questionnaire_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.radio_button_answer
    ADD CONSTRAINT fkrg3f194uff3ep0r6mwl0jkr7a FOREIGN KEY (id)
    REFERENCES public.answer_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS radio_button_answer_pkey
    ON public.radio_button_answer(id);


ALTER TABLE IF EXISTS public.slider_answer
    ADD CONSTRAINT fkbk854xjlambg2h8orrg5ron3j FOREIGN KEY (id)
    REFERENCES public.answer_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS slider_answer_pkey
    ON public.slider_answer(id);


ALTER TABLE IF EXISTS public.text_answer
    ADD CONSTRAINT fk1t1tuwl70ymqtc8kt93ytk7ko FOREIGN KEY (id)
    REFERENCES public.answer_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS text_answer_pkey
    ON public.text_answer(id);


ALTER TABLE IF EXISTS public.time_answer
    ADD CONSTRAINT fkmsbttyawjawy8v5cpydnhwtct FOREIGN KEY (id)
    REFERENCES public.answer_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS time_answer_pkey
    ON public.time_answer(id);

END;